### ISSUE TITLE
TryLibrary's internal function calls are inefficient

### ISSUE THREAD

**Issue by Validark** [F3XTeam/RBX-Try-Library#3]
function `Catch` internally calls `Try`, as does function `Retry`

Perhaps they should transform the Attempt currently open instead of generating a new Attempt? Just seems wasteful to me.

One `Try` call from the user should create one `Attempt`.

**Comment by GigsD4X** [comment]
I agree, this was definitely very inconsistent and unpredictable. Just pushed 736af3be622eade2b0e7034d731f79c19f87fe08 to deal with these issues, let me know if you think this solves this 👍
